app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    group: email-group
    topics:
      email: email


server:
  port: 8100

spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ivanemail1234567890@gmail.com
    password: xdux kmya woic vnlf
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 10000
          timeout: 10000
          write timeout: 10000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    debug: true

logging:
  file:
    path: ./EmailService/logs
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

