app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topics:
      email: email
  transport:
    type: ${TRANSPORT_TYPE}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}
  student-service:
    url: ${STUDENT_SERVICE_URL}

server:
  port: ${GRADE_PORT}

spring:
  application:
    name: grade-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui