app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      email: email
  transport:
    type: KAFKA
  notification-service:
    url: http://localhost:8100

server:
  port: 8099

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  file:
    path: ./StudentService/logs
  level:
    root: info
    org:
      springframework:
        web: warn
      hibernate: error
    web: warn

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui